spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: airbnb

  datasource:
    url: ${DB_URL}?serverTimezone=Europe/Moscow
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Moscow
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  jackson:
    time-zone: Europe/Moscow

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS}

server:
  port: 28800

logging:
  level:
    ru.vova.airbnb: DEBUG
    org.springframework.security: INFO