spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: airbnb

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  jackson:
    time-zone: Europe/Moscow

app:
  datasource:
    core:
      xa-class-name: org.postgresql.xa.PGXADataSource
      url: ${CORE_DB_URL:jdbc:postgresql://localhost:5433/airbnb_core}
      username: ${CORE_DB_USERNAME:airbnb}
      password: ${CORE_DB_PASSWORD:airbnb}
    property:
      xa-class-name: org.postgresql.xa.PGXADataSource
      url: ${PROPERTY_DB_URL:jdbc:postgresql://localhost:5434/airbnb_property}
      username: ${PROPERTY_DB_USERNAME:airbnb}
      password: ${PROPERTY_DB_PASSWORD:airbnb}
  jpa:
    ddl-auto: update
    show-sql: true
    format-sql: true
    jdbc-time-zone: Europe/Moscow
    dialect: org.hibernate.dialect.PostgreSQLDialect
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS}

server:
  port: 28800

logging:
  level:
    ru.vova.airbnb: DEBUG
    org.springframework.security: INFO