package ru.vova.airbnb.entity;

public enum Privilege {
    BOOKING_CREATE,
    BOOKING_UPDATE,
    BOOKING_DELETE,
    BOOKING_PAY,
    BOOKING_CONFIRM,
    BOOKING_REJECT,
    BOOKING_FORCE_STATUS,
    BOOKING_SUPPORT_REQUEST,
    BOOKING_SUPPORT_PROCESS,
    BOOKING_VIEW_OWN,
    BOOKING_VIEW_ANY,
    BOOKING_LIST_HOST,
    BOOKING_LIST_GUEST,
    PROPERTY_CREATE,
    PROPERTY_VIEW,
    PROPERTY_VIEW_HOST_LIST
}
